namespace EscolaPro.Core.Model
{
    public enum TipoAnexoEnum
    {
        Outros = 0,
        DocumentoUnidade = 1,
        HistoricoOcorrencia = 2,
        TermoCompromissoEstagio = 3,
        ContratoTrabalho = 4,
        ExameMedico = 5,
        ComprovanteEndereco = 6,
        CopiaRG = 7,
        CopiaCPF = 8,
        CertidaoNascimento = 9,
        ContratoPrestacaoServico = 10,
        ReciboPagamento = 11,
        ComprovanteTransacaoBancaria = 12,
        NotaFiscal = 13,
        BoletoBancario = 14,
        GuiaImposto = 15,
        Pedido = 16,
        Orcamento = 17,
        ComprovanteRetornoItau = 18,
        Foto3X4 = 19,
        HistoricoEscolar = 20,
        ComprovanteAlfabetizacao = 21,
        Reservista = 22,
        TituloEleitor = 23,
        CNH = 24,
        Redacao = 25,
        DeclaracaoPendenciaDocumental = 26,
        CopiaRGResponsavel = 27,
        CopiaCPFResponsavel = 28,
        RG_CPF = 29,
        RG_CPF_TituloEleitor = 30,
        CopiaRGcomCPFResponsavel = 31,
        ComprovanteBolsaConvenio = 32,
        ContratoProcuracaoEja = 33,
        AtestadoEliminacaooDisciplinaOriginal = 34, 
        AssinaturaRequerimentoOuQuestionárioTeste = 35,
        HistoricoEscolarEnsinoMedio = 36,
        PublicacaoLaudaGDAE = 37,
        AtestadoMedico = 38
    }
}