export const Perfis: Array<{label: string, value: number }> = [
    { label: 'Administrador',                       value: 1 },
    { label: 'Gerência',                            value: 2 },
    { label: 'Financeiro Sênior',                   value: 3 },
    { label: 'Financeiro Pleno',                    value: 4 },
    { label: 'Financeiro Junior',                   value: 5 },
    { label: 'Supervisor de Unidades',              value: 6 },
    { label: 'Analista de Suporte Administrativo',  value: 7 },
    { label: 'Analista de Suporte RH',              value: 8 },
    { label: 'Analista de Suporte Jurídico',        value: 9 },
    { label: 'Analista de Suporte Atendimento',     value: 10 },
    { label: 'Supervisor de Suporte',               value: 11 },
    { label: 'Líder Equipe',                        value: 12 },
    { label: 'Atendente',                           value: 13 },
    { label: 'Aluno',                               value: 14 },
    { label: 'Jurídico Parceiro',                   value: 15 },
    { label: 'Terceiro',                            value: 16 },
    { label: 'Visitante',                           value: 17 },
    { label: 'Professor',                           value: 18 },
    { label: 'Lead Secretária',                     value: 19 },
    { label: 'Lead Mídias',                         value: 20 },
    { label: 'Lead Divulgador',                     value: 21 },
];