export enum ComoConheceuEnum {
    Indicacao = 1,
    Google = 2,
    Facebook = 3,
    Instagram = 4,
    PassouEmfrente = 5,
    Whatsapp = 6,
    FaixasNaRua = 7,
    Panfleto = 8,
    Onibus = 9,
    CartazEmComercio = 10,
    Jornal = 11,
    Televisao = 12,
    Radio = 13,
    ChatOnline = 14,
    ListaTelefonica = 15,
    TeleResponde = 16,
    Pesquisa = 17,
    Outdoor = 18,
    Muro = 19
}